import Head from 'next/head';
import { Provider } from 'react-redux';
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import reducers from '../redux/reducers';
import PostsIndex from './PostsIndex';
// import Image from 'next/image';

export default function Home() {
  const store = createStore(reducers, compose(applyMiddleware(thunk)));
  return (
    <Provider store={store}>
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.ico" />
        </Head>
        <PostsIndex />
      </div>
    </Provider>
  );
}
